import http from "node:http";
import fs from "node:fs";
import path from "node:path";
import {execFile} from "node:child_process";
import {fileURLToPath} from "node:url";

const ROOT=process.env.SIGNAL_INTERPRETER_REPO?path.resolve(process.env.SIGNAL_INTERPRETER_REPO):path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../..");
const OBS=path.join(ROOT,"observations"),BATCHES=path.join(OBS,"batches"),LATEST=path.join(OBS,"latest");
const PORT=Number(process.env.SIGNAL_OBSERVATION_PORT||8788),MAX_BYTES=5*1024*1024,COMMIT_WINDOW_MS=Number(process.env.SIGNAL_OBSERVATION_COMMIT_WINDOW_MS||600000);
let syncTimer=null,syncRunning=false,dirty=false,forceNext=false;
const iso=()=>new Date().toISOString();
function write(file,data){fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,data)}
function runGit(args){return new Promise((resolve,reject)=>execFile("git",args,{cwd:ROOT,windowsHide:true},(error,stdout,stderr)=>error?reject(new Error((stderr||stdout||error.message).trim())):resolve((stdout||"").trim())))}
function scheduleGitSync(force=false){dirty=true;forceNext=forceNext||force;clearTimeout(syncTimer);syncTimer=setTimeout(runGitSync,force?5000:COMMIT_WINDOW_MS)}
async function runGitSync(){if(syncRunning||!dirty)return;syncRunning=true;dirty=false;const force=forceNext;forceNext=false;try{await runGit(["add","observations"]);const status=await runGit(["status","--porcelain","--","observations"]);if(status)await runGit(["commit","-m",force?"diagnostic: publish critical observation batch":"diagnostic: publish observation batch"]);await runGit(["push","origin","main"]);console.error("[observation-reporter]",iso(),"git-sync ok")}catch(error){dirty=true;console.error("[observation-reporter]",iso(),"git-sync failed:",String(error));clearTimeout(syncTimer);syncTimer=setTimeout(runGitSync,COMMIT_WINDOW_MS)}finally{syncRunning=false}}
function sanitizeBatch(input){if(!input||input.schema!=="signal-interpreter-observation-batch/v1")throw new Error("Schema de batch no soportado");const events=Array.isArray(input.events)?input.events.slice(0,200):[];const safeEvents=events.map(e=>{const out={};for(const k of ["schema","id","sequence","timestamp","ingestedAt","level","category","component","phase","action","outcome","traceId","operationId","parentEventId","attempt","durationMs","session","environment","expected","observed","reasonCode","error","metrics","context","privacy"])if(Object.hasOwn(e,k))out[k]=e[k];return out});return{schema:input.schema,batchId:String(input.batchId||""),createdAt:String(input.createdAt||iso()),trigger:String(input.trigger||"scheduled"),extensionVersion:String(input.extensionVersion||"unknown"),summary:input.summary&&typeof input.summary==="object"?input.summary:{},events:safeEvents}}
const server=http.createServer((req,res)=>{res.setHeader("Access-Control-Allow-Origin","*");res.setHeader("Access-Control-Allow-Headers","Content-Type");res.setHeader("Access-Control-Allow-Methods","POST,OPTIONS,GET");if(req.method==="OPTIONS"){res.writeHead(204);return res.end()}if(req.method==="GET"&&req.url==="/health"){res.writeHead(200,{"Content-Type":"application/json"});return res.end(JSON.stringify({ok:true,service:"signal-observation-reporter",port:PORT,repo:ROOT,dirty,gitSyncRunning:syncRunning}))}if(req.method!=="POST"||req.url!=="/v1/observation-batch"){res.writeHead(404);return res.end("Not found")}let size=0,chunks=[];req.on("data",chunk=>{size+=chunk.length;if(size>MAX_BYTES){req.destroy();return}chunks.push(chunk)});req.on("end",()=>{try{const batch=sanitizeBatch(JSON.parse(Buffer.concat(chunks).toString("utf8")));if(!batch.batchId)throw new Error("batchId requerido");write(path.join(BATCHES,batch.batchId+".json"),JSON.stringify(batch,null,2)+"\n");const latest={...batch,receivedAt:iso()};write(path.join(LATEST,"latest.json"),JSON.stringify(latest,null,2)+"\n");const s=batch.summary||{};const md=["# Signal Interpreter · latest observation","","- Batch: `"+batch.batchId+"`","- Recibido: `"+latest.receivedAt+"`","- Trigger: "+batch.trigger,"- Extensión: "+batch.extensionVersion,"- Eventos: "+Number(s.eventsTotal||batch.events.length),"- Errores: "+Number(s.errors||0),"- Warnings: "+Number(s.warnings||0),"- Secuencia: "+Number(s.firstSequence||0)+" → "+Number(s.lastSequence||0),"","## Categorías","```json",JSON.stringify(s.categories||{},null,2),"```","","## Acciones","```json",JSON.stringify(s.actions||{},null,2),"```",""];write(path.join(LATEST,"latest-summary.md"),md.join("\n"));scheduleGitSync(Boolean(s.critical||Number(s.errors||0)>0));res.writeHead(202,{"Content-Type":"application/json"});res.end(JSON.stringify({ok:true,accepted:true,batchId:batch.batchId,lastSequence:s.lastSequence||null,gitSync:"queued"}))}catch(error){res.writeHead(400,{"Content-Type":"application/json"});res.end(JSON.stringify({ok:false,error:String(error)}))}})});
server.listen(PORT,"127.0.0.1",()=>console.error("[observation-reporter]",iso(),"listening on http://127.0.0.1:"+PORT,"repo="+ROOT));