(function(){
"use strict";
var $=function(id){return document.getElementById(id)};
var items=[],sessions=[],activeSessionId=null,currentSession=null,activeSpeaker="CLIENTE",view="timeline",autoScroll=true,focusMode=false,sessionSaveTimer=null,captureState="stopped";
var sizes={compact:{width:430,height:700},normal:{width:760,height:760},reading:{width:1200,height:820}},seen={CLIENTE:0,YO:0};
function esc(v){return String(v||"").replace(/[&<>"']/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]})}
function time(v){try{return new Date(v).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit",second:"2-digit"})}catch(_){return"—"}}
function sessionParts(s){try{var u=new URL(String(s&&s.sourceUrl||"")),host=u.hostname.replace(/^www\./,""),path=(u.pathname||"/")+(u.search||"");return{title:s&&s.title||host||"Sesión",url:host+(path.length>48?path.slice(0,45)+"…":path)}}catch(_){return{title:s&&s.title||"Sesión",url:String(s&&s.sourceUrl||"")}}}
function normalizeSession(s){s=Object.assign({segments:[],activeSpeaker:"CLIENTE",view:"timeline",fontSize:20,autoScroll:true,compactDensity:false,voiceMap:{A:"CLIENTE",B:"YO"}},s||{});s.segments=SignalDialogue.sortSegments(Array.isArray(s.segments)?s.segments.slice(-200):[]);return s}
function upsertSession(s){if(!s||!s.id)return;var n=normalizeSession(s),i=sessions.findIndex(function(x){return x.id===n.id});if(i<0)sessions.push(n);else sessions[i]=n}
function recomputeSeen(){seen={CLIENTE:0,YO:0};items.forEach(function(x){var k=x.speaker==="YO"?"YO":"CLIENTE";seen[k]++})}
function renderSessionTabs(){var host=$("sessionTabsList");host.replaceChildren();if(!sessions.length){var e=document.createElement("span");e.className="session-empty";e.textContent="Abre la consola desde una pestaña para crear una sesión.";host.appendChild(e);return}sessions.forEach(function(s){var b=document.createElement("div"),o=document.createElement("button"),c=document.createElement("button"),p=sessionParts(s);b.className="session-tab"+(s.id===activeSessionId?" active":"");o.className="session-tab-main";o.type="button";o.innerHTML="<span>"+esc(p.title)+"</span><small>"+esc(p.url)+"</small>";o.onclick=function(){activateSession(s.id)};c.className="session-tab-close";c.type="button";c.textContent="×";c.onclick=function(e){e.stopPropagation();deleteSession(s.id)};b.appendChild(o);b.appendChild(c);host.appendChild(b)})}
async function deleteSession(id){var s=sessions.find(function(x){return x.id===id});if(!s||!confirm("Borrar esta sesión y su historial de transcripción?"))return;var r=await chrome.runtime.sendMessage({type:"DELETE_SIGNAL_SESSION",sessionId:id});if(r&&r.ok){sessions=sessions.filter(function(x){return x.id!==id});activeSessionId=r.activeSessionId||null;currentSession=null;items=[];if(r.session){upsertSession(r.session);applySession(r.session)}else{activeSpeaker="CLIENTE";render()}}else{$("groqText").textContent="ERROR";$('participantDetection').textContent=String(r&&r.error||"No se pudo borrar")}}
function applySession(s){currentSession=normalizeSession(s);activeSessionId=currentSession.id;items=currentSession.segments.slice(-200);activeSpeaker=currentSession.activeSpeaker||"CLIENTE";view=currentSession.view==="triptych"?"triptych":"timeline";autoScroll=currentSession.autoScroll!==false;var f=Number(currentSession.fontSize)||20;$("fontSize").value=String(f);$("fontSizeValue").textContent=f+" px";$("autoScroll").checked=autoScroll;$("compactDensity").checked=!!currentSession.compactDensity;document.documentElement.style.setProperty("--font",f+"px");document.body.classList.toggle("compact",!!currentSession.compactDensity);$("timeline").classList.toggle("hidden",view!=="timeline");$("triptych").classList.toggle("hidden",view!=="triptych");document.querySelectorAll("[data-view]").forEach(function(b){b.classList.toggle("active",b.dataset.view===view)});render()}
function persistSessionPatch(patch,immediate){if(!activeSessionId)return;currentSession=Object.assign({},currentSession,patch);upsertSession(currentSession);renderSessionTabs();clearTimeout(sessionSaveTimer);var send=function(){chrome.runtime.sendMessage({type:"UPDATE_SIGNAL_SESSION",sessionId:activeSessionId,patch:patch}).catch(function(){})};if(immediate)send();else sessionSaveTimer=setTimeout(send,160)}
async function activateSession(id){var r=await chrome.runtime.sendMessage({type:"ACTIVATE_SIGNAL_SESSION",sessionId:id});if(r&&r.ok&&r.session){upsertSession(r.session);applySession(r.session);return}$("groqText").textContent="ERROR";$('participantDetection').textContent=String(r&&r.error||"No se pudo activar")}
function makeTurn(x){var n=document.createElement("article");n.className="turn "+(x.speaker==="YO"?"me":"client");n.innerHTML='<div class="turn-meta"><span class="name">'+esc(x.speaker)+'</span><span class="time">'+time(x.timestamp)+'</span></div><div class="text">'+esc(x.text)+'</div>';return n}
function render(){
  renderSessionTabs();$("sessionSource").textContent=currentSession?sessionParts(currentSession).url:"Sin URL de sesión";$("segmentCount").textContent=String(items.length);$("clientCount").textContent=seen.CLIENTE;$("meCount").textContent=seen.YO;
  $("participantSummary").textContent="2 PARTICIPANTES · "+((seen.CLIENTE?1:0)+(seen.YO?1:0))+" CON TEXTO";$("activeSpeakerTitle").textContent=activeSpeaker;
  var t=$("timeline");t.replaceChildren();if(!items.length){var e=document.createElement("p");e.className="empty";e.textContent="Esperando transcripción de Groq…";t.appendChild(e)}else{items.forEach(function(x){t.appendChild(makeTurn(x))});if(autoScroll)t.scrollTop=t.scrollHeight}
  var c=$("clientLane"),m=$("meLane");c.replaceChildren();m.replaceChildren();items.forEach(function(x){var n=document.createElement("div");n.className="lane-item";n.innerHTML="<time>"+time(x.timestamp)+"</time><p>"+esc(x.text)+"</p>";(x.speaker==="YO"?m:c).appendChild(n)});c.scrollTop=c.scrollHeight;m.scrollTop=m.scrollHeight;
  $("captureToggle").textContent=captureState==="connected"?"DETENER CAPTURA":"INICIAR CAPTURA";$("captureToggle").disabled=!currentSession;$("groqDot").classList.toggle("ok",captureState==="connected");$("groqStatus").textContent=captureState==="connected"?"GROQ · CAPTURANDO":captureState==="error"?"GROQ · ERROR":"GROQ · DETENIDO";$("groqText").textContent=captureState==="connected"?"Capturando":captureState==="error"?"Error":"Detenido";
  $("audioText").textContent=captureState==="connected"?"Capturando pestaña":"Esperando";$("micText").textContent=captureState==="connected"?"Capturando":"Esperando";
  $("timeline").classList.toggle("hidden",view!=="timeline");$("triptych").classList.toggle("hidden",view!=="triptych");if(focusMode){$("focusOverlay").classList.remove("hidden");var last=items[items.length-1];$("focusLabel").textContent=last?last.speaker:activeSpeaker;$("focusText").textContent=last?last.text:"Esperando señal…"}else $("focusOverlay").classList.add("hidden");
}
function addSegment(e){var id=e.sessionId||activeSessionId;if(!id)return;var s=sessions.find(function(x){return x.id===id});if(!s)return;var seg=e.segment||e,text=String(seg.text||e.text||"").trim();if(!text)return;var sid=seg.id||e.segmentId||("groq-"+Date.now());if((s.segments||[]).some(function(x){return x.id===sid}))return;var x={id:sid,speaker:seg.speaker||e.speaker||"CLIENTE",text:text,timestamp:seg.timestamp||e.timestamp||new Date().toISOString(),source:seg.source||e.source||"groq",reason:seg.reason||"groq-transcription"};s.segments=SignalDialogue.sortSegments((s.segments||[]).concat(x).slice(-200));upsertSession(s);if(id===activeSessionId){items=s.segments.slice(-200);currentSession=s;recomputeSeen();render()}}
function handle(e){if(!e||!e.type)return;if(e.type==="signal.session.active"||e.type==="signal.session.updated"){var incoming=e.session?normalizeSession(e.session):null;if(incoming)upsertSession(incoming);activeSessionId=e.sessionId||activeSessionId;var s=sessions.find(function(x){return x.id===activeSessionId});if(s)applySession(s);return}if(e.type==="signal.session.deleted"){sessions=sessions.filter(function(s){return s.id!==e.sessionId});activeSessionId=e.activeSessionId||null;var next=sessions.find(function(s){return s.id===activeSessionId});if(next)applySession(next);else{currentSession=null;items=[];render()}return}if(e.type==="signal.groq.status"){captureState=e.status||"stopped";render();return}if(e.type==="signal.transcript.segment"){addSegment(e);return}if(e.type==="signal.transcript.clear"){if(e.sessionId===activeSessionId){items=[];if(currentSession)currentSession.segments=[];render()}return}}
async function capture(){if(!currentSession)return{ok:false,error:"No hay sesión activa"};if(captureState==="connected")return chrome.runtime.sendMessage({type:"SIGNAL_GROQ_CAPTURE_STOP",sessionId:currentSession.id}).then(function(r){return r});try{var tab=await chrome.tabs.get(currentSession.sourceTabId);var id=await chrome.tabCapture.getMediaStreamId({targetTabId:tab.id});return chrome.runtime.sendMessage({type:"SIGNAL_GROQ_CAPTURE_START",sessionId:currentSession.id,audioStreamId:id});}catch(error){captureState="error";$("groqText").textContent=String(error);render();return{ok:false,error:String(error)}}}
function exportDiagnostic(){chrome.storage.local.get(["effectifConfig","effectifState","signalInterpreterSessions","signalInterpreterActiveSessionId","effectifLastEvent","effectifTelemetryHealth"]).then(function(stored){return Promise.all([KhoraTelemetryDB.getEvents(),KhoraTelemetryDB.getSnapshots(),KhoraTelemetryDB.getAllSignalSegments(),KhoraTelemetryDB.stats()]).then(function(rs){var c=Object.assign({},stored.effectifConfig||{});if(c.groqApiKey)c.groqApiKey="[REDACTED]";var payload={schema:"signal-interpreter-diagnostic/v4",exportedAt:new Date().toISOString(),report:{purpose:"Diagnóstico de captura de audio Groq, transcripción y persistencia por sesión",eventsCount:rs[0].length,signalSegmentsCount:rs[2].length},groqCapture:stored.effectifState&&stored.effectifState.groqCapture||null,telemetryHealth:stored.effectifTelemetryHealth||null,lastEvent:stored.effectifLastEvent||null,config:c,state:stored.effectifState||{},activeSessionId:stored.signalInterpreterActiveSessionId||null,sessions:stored.signalInterpreterSessions||[],events:rs[0],platformSnapshots:rs[1],signalSegments:rs[2],telemetry:rs[3]};var b=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="signal-interpreter-groq-"+new Date().toISOString().replace(/[:.]/g,"-")+".json";a.click();setTimeout(function(){URL.revokeObjectURL(u)},2000)})})}
function setView(v){view=v;persistSessionPatch({view:v},true);render()}
function applySize(name){var x=sizes[name];if(!x)return;chrome.windows.getCurrent().then(function(w){return chrome.windows.update(w.id,x)}).catch(function(){})}
function saveBounds(){chrome.windows.getCurrent().then(function(w){localStorage.setItem("signalLiveBounds",JSON.stringify({left:w.left,top:w.top,width:w.width,height:w.height,state:w.state}))}).catch(function(){})}
function restoreBounds(){try{var x=JSON.parse(localStorage.getItem("signalLiveBounds")||"null");if(x)chrome.windows.getCurrent().then(function(w){chrome.windows.update(w.id,{left:x.left,top:x.top,width:x.width,height:x.height,state:x.state==="normal"?"normal":w.state})}).catch(function(){})}catch(_){} }
document.querySelectorAll("[data-speaker]").forEach(function(b){b.onclick=function(){activeSpeaker=b.dataset.speaker;persistSessionPatch({activeSpeaker:activeSpeaker},true);render()}});
document.querySelectorAll("[data-view]").forEach(function(b){b.onclick=function(){setView(b.dataset.view)}});
$("captureToggle").onclick=function(){capture().then(function(r){if(r&&r.ok){captureState=captureState==="connected"?"stopped":"connected"}render()})};
$("clear").onclick=function(){if(activeSessionId)chrome.runtime.sendMessage({type:"CLEAR_SIGNAL_INTERPRETER_TRANSCRIPT",sessionId:activeSessionId})};
$("exportDiagnostic").onclick=exportDiagnostic;
$("syncDiagnostic").onclick=function(){var b=$("syncDiagnostic");b.disabled=true;chrome.runtime.sendMessage({type:"SIGNAL_OBSERVATION_SYNC_NOW"}).finally(function(){b.disabled=false})};
$("scrollLive").onclick=function(){autoScroll=true;$("autoScroll").checked=true;$("timeline").scrollTop=$("timeline").scrollHeight};
$("focusBtn").onclick=function(){focusMode=!focusMode;render()};$("focusExit").onclick=function(){focusMode=false;render()};
$("sizeMenu").onclick=function(){$("sizeMenuPanel").classList.toggle("hidden")};document.querySelectorAll("[data-size]").forEach(function(b){b.onclick=function(){applySize(b.dataset.size);$("sizeMenuPanel").classList.add("hidden")}});
$("fontSize").oninput=function(){document.documentElement.style.setProperty("--font",this.value+"px");$("fontSizeValue").textContent=this.value+" px";persistSessionPatch({fontSize:Number(this.value)},false)};
$("autoScroll").onchange=function(){autoScroll=this.checked;persistSessionPatch({autoScroll:autoScroll},true)};$("compactDensity").onchange=function(){document.body.classList.toggle("compact",this.checked);persistSessionPatch({compactDensity:this.checked},true)};
$("timeline").onscroll=function(){var t=$("timeline");autoScroll=t.scrollHeight-t.scrollTop-t.clientHeight<80;$("autoScroll").checked=autoScroll};
document.addEventListener("keydown",function(e){if(e.target&&/TEXTAREA|INPUT/.test(e.target.tagName))return;if(e.key==="1"){activeSpeaker="CLIENTE";persistSessionPatch({activeSpeaker:activeSpeaker},true);render()}if(e.key==="2"){activeSpeaker="YO";persistSessionPatch({activeSpeaker:activeSpeaker},true);render()}if(e.key.toLowerCase()==="t")setView("timeline");if(e.key.toLowerCase()==="g")setView("triptych");if(e.key.toLowerCase()==="f"){focusMode=true;render()}if(e.key==="Escape"){focusMode=false;render()}});
$("sendYo").onclick=function(){var v=$("yo").value.trim();if(!v||!activeSessionId)return;chrome.runtime.sendMessage({type:"ADD_SIGNAL_SESSION_SEGMENT",sessionId:activeSessionId,text:v,speaker:"YO"}).then(function(r){if(r&&r.ok&&r.session){upsertSession(r.session);applySession(r.session);$("yo").value=""}})};
chrome.runtime.onMessage.addListener(function(m){if(m&&m.type==="SIGNAL_INTERPRETER_EVENT")handle(m.event)});
chrome.runtime.sendMessage({type:"GET_SIGNAL_INTERPRETER_STATE"}).then(function(r){if(!r||!r.ok)return;sessions=(r.sessions||[]).map(normalizeSession);activeSessionId=r.activeSessionId||null;var s=sessions.find(function(x){return x.id===activeSessionId})||sessions[sessions.length-1];if(s)applySession(s);captureState=r.groq&&r.groq.status||"stopped";render();restoreBounds()}).catch(function(){restoreBounds();render()});
window.addEventListener("beforeunload",function(){saveBounds();chrome.runtime.sendMessage({type:"SIGNAL_LIVE_CONSOLE_CLOSE"}).catch(function(){})});
render();
})();
